### ISSUE TITLE
package-update not possible

### ISSUE THREAD

**Issue by yunex-ts** [opsi-org/opsi-docker#1]
There is no possibilty to automate the repo update, right?
Or is it possible via rpc?

**Comment by fkalweit** [comment]
Do you mean the opsi package repositories or the server packages? 

The opsi packages can be kept up-to-date with the [opsi-package-updater](https://docs.opsi.org/opsi-docs-de/4.3/server/components/commandline.html#server-components-opsi-package-updater)


The containers can be updated with `opsi-server.sh upgrade.`

**Comment by yunex-ts** [comment]
Hey fkalweit,
I mean the automatic run of the package updater. 

In that kind of environments it is not usual to setup cron jobs in container. So they have to be run manually or via some scheduled task on external systems that start package update within container.

**Comment by fkalweit** [comment]
You can execute the command `docker compose exec opsi-server opsi-package-updater -vv update` on the Docker host. 
A cron job could then also be set up for this command. 


Maybe we would add the exec command to the opsi-server.sh script.
We are also working on other methods to update the packages on the opsi-server .

I hope this helps.

**Comment by j-a-n** [comment]
Please use our forum at https://forum.opsi.org for support questions or conclude a support contract with uib at https://www.uib.de/en/support.
