### ISSUE TITLE
Question about config and depot

### ISSUE THREAD

**Issue by Sythelux** [opsi-org/opsi-docker#3]
Apologies in advance for using the Issue Ticket system for a comprehension question.

the docker compose file has the possibility to switch between config server and depot server. for a successfully running OPSI setup I need both. why are there not both servers within the docker-compose?

Do you have a suggestion how I could make it work?

**Comment by fkalweit** [comment]
Hello, 

in the standard case the Configserver acts as Configserver and depot. Only the Configserver is required for operation. If you serve several locations, you can set up depot servers at the locations. The depot servers do not have their own database, but hold the installation files for the clients and forward things like Wake on Lan to the clients.

Best regards Fabian

**Comment by Sythelux** [comment]
Thank you. I wasn't aware, that the Config Server is also a depot server. It somehow is never mentioned in the docs, but it is probably obvious for the developers. then i only need a Config Server.


This can be closed then.
