### ISSUE TITLE
${OPSI_HOST_KEY} wird durch "opsiconfd setup" überschrieben

### ISSUE THREAD

**Issue by itadmin-irlbacher** [opsi-org/opsi-docker#4]
Aktuell habe ich das Problem das der in "opsi-server.env" gesetzte Hostkey nicht übernommen wird. Die Funktion "backend_config_depotserver" setzt den Key zunächst richtig, allerdings wird Hostkey nach dem Aufruf von "opsiconfd setup" wieder auf einen anderen Wert gestetzt den ich nirgends finde.

Gewünschter Key: e1fb17f7ef69c32c6c6328dd20e365a9
Durch Setup gesetzter Key: a8c1e06a773a2013c59947969e5d38c3

**Abschnitt aus "entrypoint.sh"**
        _if [ "${OPSI_HOST_ROLE}" = "depotserver" ]; then
                backend_config_depotserver
                opsiconfd setup --log-level-stderr 6
        else
                backend_config_configserver
                opsiconfd setup --log-level-stderr 6
        fi_

**Comment by j-a-n** [comment]
Bitte nutzen Sie unser Forum unter https://forum.opsi.org für Supportfragen oder schließen Sie einen Supportvertrag mit uib unter https://www.uib.de/de/support ab.
